name    'cloudscaling-scaleio_fuel'
version '1.0.0'
source 'UNKNOWN'
author 'EMC'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'ScaleIO Fuel plugin puppets'
project_page 'UNKNOWN'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
